# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruffのバージョンは、pyproject.tomlのruffバージョンと合わせることが望ましい
    rev: v0.11.12
    hooks:
    # 自動修正（より積極的な修正を含む）
    -   id: ruff
        args: [--fix, --unsafe-fixes]
    # コードをフォーマットする（最後に実行して一貫したスタイルを確保）
    -   id: ruff-format
